version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "4000:4000"
    depends_on:
      - mongodb
    env_file:
      - ./server/.env

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "80:80"

  mongodb:
    image: mongo:latest
    restart: on-failure
    ports:
      - "27017:27017"