version: '3.8'

services:
  client:
    image: devln/diplom-client:1.0.0
    container_name: client
    restart: on-failure
    ports:
      - "80:80"
    networks:
      - mynetwork

  server:
    image: devln/diplom-server:1.0.1
    container_name: server
    restart: on-failure
    ports:
      - "4000:4000"
    depends_on:
      - mongodb
    # environment:
    #   - JWT_SECRET=super_secret
    #   - SD_BASE_URL=localhost
    #   - LLAMA_BASE_URL=localhost
    #   - DB_HOST=mongodb
    #   - DB_PORT=27017
    #   - DB_NAME=test
    #   - SITE_URL=localhost
    env_file:
      - .env
    networks:
      - mynetwork

  mongodb:
    image: mongo:4.4.29
    container_name: diplom-mongo
    restart: on-failure
    ports:
      - "27017:27017"
    networks:
      - mynetwork

networks:
  mynetwork:
