version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "4000:4000"
    depends_on:
      - mongodb
    env_file:
      - ./server/.env
    container_name: server

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "80:80"
    container_name: client

  mongodb:
    image: mongo:4.4.29
    restart: on-failure
    ports:
      - "27017:27017"
    container_name: mongodb
